# Generated by Django 4.1.7 on 2023-02-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicsappointment",
            name="category",
            field=models.CharField(
                choices=[
                    ("MALARIA", "MALARIA"),
                    ("TYPHOID", "TYPHOID"),
                    ("SURGERY", "SURGERY"),
                    ("MENTAL HEALTH", "MENTAL HEALTH"),
                    ("OTHER", "OTHER"),
                ],
                default="MALARIA",
                max_length=20,
            ),
        ),
    ]
