# Generated by Django 4.1.7 on 2023-02-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_medicsappointment_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicsappointment",
            old_name="session",
            new_name="appointment_session",
        ),
        migrations.AddField(
            model_name="medicsappointment",
            name="appointment_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="medicsappointment",
            name="doctor",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.doctor"
            ),
        ),
    ]
